# Generated by Django 5.2.12 on 2026-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('scan_image', models.ImageField(upload_to='scans/')),
                ('prediction_result', models.CharField(max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(blank=True, max_length=50)),
                ('cognitive_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
